FROM @@image@@

RUN mkdir -p /src/opt/conjur/project

WORKDIR /src/opt/conjur/project

COPY Gemfile ./
COPY Gemfile.lock ./

RUN bundle config set --local deployment 'true' && \
    bundle config set --local path 'vendor/bundle' && \
    bundle

COPY . .
ADD debify.sh /

WORKDIR /src
